# Generated by Django 5.0 on 2023-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_relation_relation_rel_relation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
